### ISSUE TITLE
Consider extending JsonApiModelBuilder to build the collection model

### ISSUE THREAD

**Issue by jimirocks** [toedter/spring-hateoas-jsonapi#12]
Currently JsonApiModelBuilder always creates instance of `JsonApiModel`  which is however not the `CollectionModel`. This effectively prevents usage in correct custom implementation of [RepresentationModelAssembler](https://docs.spring.io/spring-hateoas/docs/1.1.1.RELEASE/api/org/springframework/hateoas/server/RepresentationModelAssembler.html) - namely there is no way how to insert `included` into such collection.

From the other point of view, JSON:API coumpound document (which is usually used as the collection representation) could be also considered not beeing representation of `CollectionModel`. So this idea is questionable.

**Comment by toedter** [comment]
This is true, but if you use the JSON:API model builder, you would probably like to use JSON:API specific features like relationships and included. You could then easily create your own ModelAssembler that provides a method `toRepresentationModel(Iterable<? extends T> entities)` that returns a RepresentetionModel<?>. In this method, you could use the builder.
