### ISSUE TITLE
Null data field in the serialized result 

### ISSUE THREAD

**Issue by peter-plochan** [toedter/spring-hateoas-jsonapi#13]
I want to render/serialize the `meta` top-level element without any data, e.g. I want to show some index with links. For this, I build "meta-only" `JsonApiModel`:
```
JsonApiModelBuilder.jsonApiModel()
        .meta("index", indexObject)
        .build();
```
And the serialized result looks like this:
```
{
  "data": null,
  "meta": {
    "index": ...
  }
}
```
Even it's not against JSON:API spec, I consider this `"data": null` element quite ugly. Is there any chance how to exclude this from the resulting document?

**Comment by toedter** [comment]
Thanks, Peter. This makes sense.

But I also support the option data being **always** rendered as an array, returning an empty array, like:

```
{
  "data": [],
  "meta": {
    "index": ...
  }
}
```

I will think about it, probably a good balance would be to erase `"data" : null` if links or meta is present, but keep `"data" : []` if the option to always render data as array was chosen.

**Comment by toedter** [comment]
Implemented in the current snapshot, will be in the next release.
