### ISSUE TITLE
Deserialization of polymorphic or generic type

### ISSUE THREAD

**Issue by jimirocks** [toedter/spring-hateoas-jsonapi#17]
Seems, the current implementation is pretty limited, able to deserialize only specific type.

Consider following use case:
```kotlin
open class A(val aProp: String)
class B(aProp: String, val bProp: String) : A(aProp)

@PostMapping
fun createA(@RequestBody a: A) {...}
```

Even if (properly typed) instance of `B` is posted, only `A` properties are deserialized. While for example when using spring-hateos with HAL it uses standard jackson way to determine the specific type. 

It would be nice to somehow enable the possibility to write generic controller method accepting request body of polymorphic type. While I studied the `Jackson2JsonApiModule` I have no clear idea how to do that. Hopefully some hook to at least provide custom deserializer or may be just allowing to deserialize into `Map` could move this on?

**Comment by toedter** [comment]
Thanks for pointing this out.
Could you provide a test written in Java to illustrate the issue on a concrete example?

**Comment by toedter** [comment]
I found an article about Jackson Polymorphic Deserialization: https://medium.com/@david.truong510/jackson-polymorphic-deserialization-91426e39b96a

Would that help in your case?

**Comment by jimirocks** [comment]
@toedter Thanks for quick reaction, I will look into this further in the end of the week

**Comment by toedter** [comment]
I think it workes very well, I have written tests for it and added a section in the documentation, see
https://toedter.github.io/spring-hateoas-jsonapi/snapshot/reference/#polymorphy

Please reopen if this is still an issue for you.
