### ISSUE TITLE
Customized ObjectMapper not used when deserializing

### ISSUE THREAD

**Issue by audax** [toedter/spring-hateoas-jsonapi#22]
In reference to  #18

Instead of using the ObjectMapper from the JsonApiConfiguration, `new ObjectMapper()` is called in [AbstractJsonApiModelDeserializer](https://github.com/toedter/spring-hateoas-jsonapi/blob/8eab6ac1101c8b70bec6328babf1288034985c45/lib/src/main/java/com/toedter/spring/hateoas/jsonapi/AbstractJsonApiModelDeserializer.java#L76).

This prevents me from specifying an abstract type mapping for my interfaces.

**Comment by toedter** [comment]
Thanks for reporting this.
Could you please provide a concrete example?
Then it's easier for me to write a test.

**Comment by audax** [comment]
Here is an integration test that uses a new IMovie interface with a single MovieImpl:
https://github.com/audax/spring-hateoas-jsonapi/commit/c58e3d113e78cd907094286f207298a96ac7a657

The configured ObjectMapper is not used AbstractJsonApiModelDeserializer which creates a blank `new ObjectMapper()` instead. I think the configured ObjectMapper is only used for serializing.

I hope the test helps and thanks for the quick response!

**Comment by toedter** [comment]
Thx @audax, I understand what you want to do now.
But it is more complicated than I thought because I can't use the very same ObjectMapper for both serialization and deserialization. I will discuss this in Gitter because I want to align here with a more generic solution that would work also with other media types.

**Comment by audax** [comment]
Excellent! I do have a workaround for now, I use different models for requests vs responses, so that I can deserialize the request-objects with a default ObjectMapper.

**Comment by toedter** [comment]
Then I close it for now, please reopen when needed.
