### ISSUE TITLE
Incorrect serialization of "to_many" relationships

### ISSUE THREAD

**Issue by peter-plochan** [toedter/spring-hateoas-jsonapi#23]
**Library version:** 0.13.0
:warning: The mentioned problem in this issue is related only to JSON:API serialization, the deserialization works well. 

We have an entity which looks like this simplified class:
```java
public class SomeEntity {
  @JsonApiId
  public String id;

  @JsonApiType
  public String type;

  public String someAttr;

  @JsonApiRelationships("relatedEntities")
  @JsonProperty("relatedEntities")
  public List<RelatedEntity> relatedEntities;
  ...
}
```
When the library serializes an instance of this class which has `relatedEntities` containing only one element, the serialized output looks like this:
```
{
  "data": {
    "id": "entity123",
    "type": "someEntity",
    "attributes": {
      "someAttr": "Attr 123",
    },
    "relationships": {
      "relatedEntities": {
        "data": {
          "id": "relEntity123",
          "type": "relatedEntity"
        }
      }
    }
  }
}
```

This is not correct because it goes against JSON:API specification of the [Resource Linkage](https://jsonapi.org/format/#document-resource-object-linkage):
> Resource linkage **MUST** be represented as one of the following:
> - null for empty to-one relationships.
> - an empty array ([]) for empty to-many relationships.
> - a single resource identifier object for non-empty to-one relationships.
> - **an array of resource identifier objects for non-empty to-many relationships.**

So the correct serialized output should look like this:
```
{
  "data": {
    "id": "entity123",
    "type": "someEntity",
    "attributes": {
      "someAttr": "Attr 123",
    },
    "relationships": {
      "relatedEntities": {
        "data": [
          {
            "id": "relEntity123",
            "type": "relatedEntity"
          }
        ]
      }
    }
  }
}
```

**Comment by toedter** [comment]
Thanks for pointing this out. 

Just a few clarifications:
* `@JsonApiRelationships()` is only used for deserialization as a hint where to put JSON:API relationships
* `@JsonApiRelationships()` has absolutely no effect on serialization
* The lib does not automatically produce relationships from DTOs

The correct way to produce the serialized JSON:API that contains relationships would be the usage of the builder.

In your example, you should annotate the `public List<RelatedEntity> relatedEntities;` with @JsonIgnore and the use the builder like

``` Java
final RepresentationModel<?> jsonApiModel =
                jsonApiModel()
                        .model(EntityModel.of(someEntity))
                        .relationshipWithDataArray("relatedEntities")
                        .relationship("relatedEntities", relatedEntities)
                        .build();
```

Then the relationship is always rendered as an array, even if it contains only one element.

Please check if this works for you.

But I am wondering why your example serializes to this result at all. I would have assumed that `relatedEntities `would appear within the `attributes` object, like `someAttr` does.

I will investigate...

**Comment by toedter** [comment]
Hm, I could not recreate your serialization example.
In my tests, an ` EntityModel.of(someEntity)` would be serialized to:

``` Json
{
  "data": {
    "id": "entity123",
    "type": "someEntity",
    "attributes": {
      "someAttr": "Attr 123",
      "relatedEntities": [{
           ...
       }]
    }
  }
}
```

which would be the expected behavior.
How did you create your example that serializes to JSON:API with relationships?

**Comment by peter-plochan** [comment]
Hi @toedter, sorry for the confusion. I forgot to include that JsonApiModelBuilder, which had only `relationships` defined (even for "to_many" relationships). If the `relationshipWithDataArray` will solve my problem, this issue is not relevant 🙂 .  Could you, please, just mention somehow the `relationshipWithDataArray` in the [Reference Documentation](https://toedter.github.io/spring-hateoas-jsonapi/release/reference/index.html#Inclusion), this can help much. Thanks.

**Comment by toedter** [comment]
No Problem, `relationshipWithDataArray ` is already in the documentation :)
