### ISSUE TITLE
Using ArrayList in .included()

### ISSUE THREAD

**Issue by YannickS99** [toedter/spring-hateoas-jsonapi#28]
I´m trying to use an ArrayList in the .included part but for some reason it´s not working. 
Here is an example of what I´m trying to do:
`List<RepresantationModel<?>> includeList = new ArrayList<>();
RepresentationModel<?> jsonApiModel = jsonApiModel().model(model).included(CollectionModel.of(includeList).build();`
Is there a way to do it this way?
Using a new .included() for every single List entry isn´t really practical. 
Sorry if this is trivial but I´m new to developing. 

Thanks for your help.

**Comment by toedter** [comment]
Thx for bringing this up. I'll take a look at it.

**Comment by YannickS99** [comment]
All right that works for me. Thank you very much for your help.

**Comment by toedter** [comment]
I included a new method in the builder to support included collections. It's in the new release 0.15.0.
