### ISSUE TITLE
Support ObjectMapper configuration for attributes de/serialization

### ISSUE THREAD

**Issue by jimirocks** [toedter/spring-hateoas-jsonapi#29]
Currently the ObjectMapper used to de/serialize objects' attributes is created internally and therefore not configurable. It prevents to use for instance different Jackson datatypes modules like `jackson-datatype-jsr310`. 

This obstacle can be moreless workarounded using custom `@Json(De)Serialize`.

**Comment by toedter** [comment]
For serialization it is supported.

Foe example, if you configure

``` Java
@Bean
JsonApiConfiguration jsonApiConfiguration() {
        return new JsonApiConfiguration()
               .withObjectMapperCustomizer(objectMapper -> {
                    objectMapper.registerModule(new JavaTimeModule());
                    objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
               });
}
```

an instance of a class like

``` Java
@Data
@NoArgsConstructor
@AllArgsConstructor
@With
public class MovieWithLastSeen {
    private String id;
    private String title;
    private Instant lastSeen;
}
```

would be serialized to:

``` JSON
{
  "data": {
    "id": "1",
    "type": "moviewithlastseens",
    "attributes": {
      "title": "Star Wars",
      "lastSeen": "2020-10-23T14:59:51Z"
    }
  }
}
```

Without the ObjectMapper configuration, `lastseen` would be serialized to

`"lastSeen":{"nano":0,"epochSecond":1603465191}`

For deserialization, other object mappers are used and this is not supported.
I will take a deeper look into deserialization.

**Comment by jimirocks** [comment]
Yeah sorry I missed it works for serialization - my usecase is rather the **deserialization**. Could I somehow help with that?

**Comment by jimirocks** [comment]
@toedter any news regarding deserialization config? Since this is serious obstacle forme, I am willing to help with implementation - just give some idea, how would you like to design it.

**Comment by jimirocks** [comment]
@toedter it seems I found a solution - please review #31

**Comment by toedter** [comment]
Thx a lot! I will review this next weekend.

**Comment by toedter** [comment]
Thanks again, I took your idea but refactored my original source base with a few optimizations. I also included your tests and they are all green now. Please check if everything is working with the current snapshot. If everything is ok, I can trigger a new release tomorrow.

**Comment by jimirocks** [comment]
Thanks for accepting - sorry I was out for weekend, but will test it today.

**Comment by toedter** [comment]
I released it yesterday, could you please test with 0.16.0?

**Comment by jimirocks** [comment]
0.16.0 is working fine for my usecase now - thanks
