### ISSUE TITLE
how to convert a POJO to JSON API string using ObjectMapper.writeValueAsString

### ISSUE THREAD

**Issue by feliperochadev** [toedter/spring-hateoas-jsonapi#3]
Hi, first of all, thanks for the project it works quite well.

I have some integration tests using `MockMvc` like the following:

```
    void get_borrower_company_details() throws Exception {
        mockMvc.perform(get(BORROWER_COMPANY_URI+"/1")
                .headers(mockMvcRequestHeaders))
                .andDo(print())
                .andExpect(status().isOk())
                .andExpect(content().json(getExpectedBorrowerCompanyDetails()));
    }
```

it basically checks if the body matches to the expected POJO String using `ObjectMapper.writeValueAsString`, the problem is, since the JSON API applies the format just using `Accept application/vnd.api+json` the header in the MockMvc request, it didn't match anymore because the POJO from `getExpectedBorrowerCompanyDetails` method is just a plain JSON.

this is the POJO:
```
@Getter
@Setter
public class BorrowerCompanyDTO extends RepresentationModel<BorrowerCompanyDTO> {
    @JsonApiId
    private long id;
    private String name;
    ...
    private String latestNote;
}
```

this is the `getExpectedBorrowerCompanyDetails` method:
```
    private String getExpectedBorrowerCompanyDetails() throws JsonProcessingException {
        var result = new BorrowerCompanyDTO();
        ...
        return mapper.writeValueAsString(result);
```

**So my question is, is there a way to convert a POJO to a JSON API compliant string?**

**Comment by toedter** [comment]
You could try configuring the ObjectMapper used in `getExpectedBorrowerCompanyDetails ` to use JSON:API serialization, like

```
    private final AutowireCapableBeanFactory beanFactory;
    ...
    ObjectMapper configureJsonApiObjectMapper(
            @NonNull ObjectMapper mapper) {
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.registerModule(new Jackson2JsonApiModule());
        mapper.setHandlerInstantiator(new JsonApiHandlerInstantiator(
                new JsonApiConfiguration(), beanFactory));

        return mapper;
    }

```

Please let me know if this helps. In the meantime, I will try this out in the example.

One small thing: if a property is named `id`, like in `BorrowerCompanyDTO `, this is automatically interpreted as JSON:API id and you would not need the `@JsonApiId` annotation.

**Comment by toedter** [comment]
Another thought: If you would use exactly the same JSON serializer for both creating the test result as well as creating what you compare the result with, then a bug in the serializer would occur on both sides and the test would be green even if the result does not look like what you would expect. So I think testing the result against a neutral expected result would be better.

**Comment by toedter** [comment]
Now the class `JsonApiMediaTypeConfiguration` is public and you can easily create an `ObjectMapper ` that serializes to JSON:API.
