### ISSUE TITLE
No CRUD-Action

### ISSUE THREAD

**Issue by jrosenhaeger** [toedter/spring-hateoas-jsonapi#30]
We want to use the library for an interface. Supports the library the following Example-Request
for a no-crud action on a resource?

POST /movies/1 HTTP/1.1
``` JSON
{
   "data": {
      "id": "1", 
      "type": "movies"
   },
   "meta": {
      "action": "doAction"
   }
}
```

If so, how can we access the meta-information?
If not, is this functionality in planning for the library?

**Comment by toedter** [comment]
Right now the deserialization of meta is not supported and not planned (yet). A workaround would be to accept the JSON string in the controller, parse the meta, and then deserialize the data part with the object mapper you could configure and cache using the `JsonApiConfiguration`. A more RESTful way of implementing actions would be to create a new REST resource like MyActionJob with a post, that takes a movie as parameter encoded in the body.
