### ISSUE TITLE
JSON API format not used when returning ResponseEntity from a coroutine

### ISSUE THREAD

**Issue by jacek-rzrz** [toedter/spring-hateoas-jsonapi#34]
👋 Hello, and thank you for an excellent library.

I have a Spring reactive application using coroutines in controller methods. There is one use case when the `spring-hateoas-jsonapi` library doesn't kick in: when my `EntityModel` is wrapped in a `ResponseEntity`.

I have made [an example repository](https://github.com/jacek-rzrz/spring-coroutines-json-api-response-entity) with controller tests to illustrate the issue. There I have four controller methods one of which doesn't return JSON:API to the client:

```kotlin
✅    fun monoEntityModel(): Mono<EntityModel<Payload>>
✅    suspend fun coroutineEntityModel(): EntityModel<Payload>
✅    fun monoResponseEntityModel(): Mono<ResponseEntity<EntityModel<Payload>>>
❌    suspend fun coroutineResponseEntityModel(): ResponseEntity<EntityModel<Payload>>
```

Do you think this could be fixable in `spring-hateoas-jsonapi`?

**Comment by toedter** [comment]
Thx for reporting this. I'll take a look at it asap.

**Comment by toedter** [comment]
I can reproduce the behavior. Currently, I have no clue, why the JSON:API serializer is not used. I will dive deeper into this and keep you posted.

**Comment by jacek-rzrz** [comment]
Curious 🤔 Thanks a lot for looking into it!

**Comment by toedter** [comment]
When you remove the suspend, it works. So somehow the Kotlin coroutine mechanism causes this behavior. Since I am not a Kotlin expert, I am stuck here. I posted this issue in the Spring HATEOAS Gitter group. If someone there can help to figure out what's happening, I will post it here.

**Comment by toedter** [comment]
I tested your demo replacing my JSON:API media type with the build-in UBER media type of Spring HATEOAS =>
The behavior is the same. My conclusion is that there is nothing I can do about that in my implementation.
Sorry about that...

Please file an issue directly in the Spring HATEOAS issue tracker: https://github.com/spring-projects/spring-hateoas/issues
