### ISSUE TITLE
Request body with JSONAPI request returns null values when using EntityModel

### ISSUE THREAD

**Issue by Hridayv** [toedter/spring-hateoas-jsonapi#35]
Hey, Thanks for this dependency, it made JSONAPI implementation really simple. I am facing this issue when trying to pass JSONAPI as a request body, the values are coming as null.

**I am using this version of dependency**
```
<dependency>
	<groupId>com.toedter</groupId>
	<artifactId>spring-hateoas-jsonapi</artifactId>
	<version>0.17.0</version>
</dependency>
```
**This is the model**
```
@NoArgsConstructor
@Data
@ToString
public class SomeObject {
	@JsonApiId
	private Long id;
	@JsonApiType
        private String type;
	private String attribute1;
	private String attribute2;
	private String attribute3;
}
```
**I have two Rest endpoints, one for converting POJO to JSONAPI format and another one for converting it back. The problem occurs when Trying to convert the JSONAPI back to POJO, its populating with null values. Attached the screenshot for the same.**
```
@GetMapping(path = "/testJsonApiRequest")
public SomeObject testJsonApiRequest(@RequestBody EntityModel<SomeObject> object)
		throws Exception {
	log.info(object.getContent().toString());
	return object.getContent();
}
```

![JsonApi-RequestBody-Null-Values](https://user-images.githubusercontent.com/48679519/124924638-474d8900-e019-11eb-8a13-d6f6e5c97165.PNG)

Can you let me know where the issue would be? Thanks in advance. :smile:

**Comment by toedter** [comment]
I get mapping does normally ignore a request body, could you please try out with a POST mapping?

**Comment by Hridayv** [comment]
Tested with POST mapping as well, but still the same issue.

**Comment by toedter** [comment]
Did you add a request header "content-type" = "application/vnd.api+json"?

**Comment by Hridayv** [comment]
adding that header I'm getting this error.

'''

java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.toedter.spring.hateoas.jsonapi.AbstractJsonApiModelDeserializer.convertToResource(AbstractJsonApiModelDeserializer.java:100) ~[spring-hateoas-jsonapi-0.17.0.jar:na]
	at com.toedter.spring.hateoas.jsonapi.AbstractJsonApiModelDeserializer.deserialize(AbstractJsonApiModelDeserializer.java:76) ~[spring-hateoas-jsonapi-0.17.0.jar:na]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3487) ~[jackson-databind-2.11.1.jar:2.11.1]
'''

**Comment by Hridayv** [comment]
It worked, Thank you for helping me out. 😄

**Comment by Hridayv** [comment]
Is there any way it works with application/json as well? in an enterprise application it would be hard for every consumer to change content-type.

**Comment by toedter** [comment]
great that I could help. It works out of the box with application/json, but then you have to POST application/json formatted JSON, having the fields on top level. The content-type header tells Spring HATEOAS which Deserializer to use.

**Comment by Hridayv** [comment]
So I tried doing that, is this the JSON to send?
```
{
   "data":{
                 "id":"1",
                  "type":"SomeApplicationName",
                  "attributes":{
                                       "attribute1":"Attribute1",
                                       "attribute2":"Attribute2",
                                       "attribute3":"Attribute3",
                                     }
             }
}
```

**Comment by toedter** [comment]
The default JSON deserializer would be used, the JSON would look like this:

{
       "type" : "SomeApplicationName",
       "attribute1" : "Attribute1",
       "attribute2" : "Attribute2",
       "attribute3" : "Attribute3"
}

**Comment by Hridayv** [comment]
Can't we deserialize the JSON API response? as we might be passing the response of one application to another application as a request.
