### ISSUE TITLE
Problem with model.included(collection)

### ISSUE THREAD

**Issue by njohannisson** [toedter/spring-hateoas-jsonapi#36]
Hi,

I attempted to use the jsonApiModel().model(u).included(c).build(); method. If c is some Collection<Entity>, I seem to end up with Entity of Entity includes in the final model. This is not working and not what the api docs said: 
"The objects of the collection are automatically wrapped into an {@link EntityModel},
     * if they are not already {@link RepresentationModel}s."
Did I fail to see something? 
Best regards,
Nico

**Comment by toedter** [comment]
Thanks for reporting this. I am on vacation and will take a look at it next week. Could you please provide a failing test or an example?

**Comment by toedter** [comment]
The following existing test shows the expected behavior:

https://github.com/toedter/spring-hateoas-jsonapi/blob/76353f47bed666310e1a0e72859caf30cde1a47c/lib/src/test/java/com/toedter/spring/hateoas/jsonapi/JsonApiModelBuilderIntegrationTest.java#L648-L671

So I am stuck here since I cannot reproduce the behavior you describe.

**Comment by njohannisson** [comment]
Hi,
sorry for the delayed response. I wrote a little demo for my problem:

```
public class Test0 {
	private ObjectMapper mapper;
	@Autowired
	JsonApiMediaTypeConfiguration config;
	@BeforeEach
	void setUpModule() {
		mapper = new ObjectMapper();
		config.configureObjectMapper(mapper);
	}
	@Data
	@AllArgsConstructor
	public class Model {
		@JsonApiId
		String id;
	}
	@Data
	@AllArgsConstructor
	public class Task {
		@JsonApiId
		String id;
	}
	@Test
	void t1() throws Exception {
		List<EntityModel<Task>> ml = new LinkedList<EntityModel<Task>>();
		ml.add(EntityModel.of(new Task("1")));
		ml.add(EntityModel.of(new Task("2")));
		ml.add(EntityModel.of(new Task("3")));
		JsonApiModelBuilder x = jsonApiModel().model(new Model("abc"));

		// RepresentationModel<?> m = x.included(ml).build(); // breaks

		// workaround:
		for (EntityModel<Task> mm : ml) {
			x.included(mm);
		}
		RepresentationModel<?> m_ok = x.build(); // works
	}
}
```
As i understood the javadocs for included(<collection>), i expected the "workaround" behaviour. The difference is, your Director is not for itself an Entity.of ... 
Hope this makes it somewhat clearer...

**Comment by toedter** [comment]
Thx, now I understood what you mean. I fixed it in the current snapshot (will be in the next release) and also wrote a test:

https://github.com/toedter/spring-hateoas-jsonapi/blob/bde51debb887d48fa566a7cd705e8e03be1ef7c8/lib/src/test/java/com/toedter/spring/hateoas/jsonapi/JsonApiModelBuilderIntegrationTest.java#L673-L696

**Comment by njohannisson** [comment]
Perfect ! 
Thank you very much.
regards
Nico
