### ISSUE TITLE
What is the proper way to handle PATCH?

### ISSUE THREAD

**Issue by sadam21** [toedter/spring-hateoas-jsonapi#51]
What is the recommended way to handle PATCH request for entities with several attributes and relationships? What should DTOs look like?

I saw example https://github.com/toedter/spring-hateoas-jsonapi/blob/master/lib/src/test/java/com/toedter/spring/hateoas/jsonapi/support/WebMvcMovieController.java .

We have to differentiate usecases:
- setting attribute/relationship to another value
- setting them to null
- property isn't sent - don't want to change property

Our solution:
We've introduced for our use case `OptionalProperty<T>` interface which is "wrapper" around entity property. Its implementation `NoneProperty` represents property which isn't sent in PATCH and `SomeProperty<T>` (property was sent).

```
class Person {
  //attributes
  private String name;
  private Integer age;

  // relationships
  private City city;
  private List<Job> jobs;
}
```
```
class PatchPerson {
  //attributes
  private OptionalProperty<String> name;
  private OptionalProperty<Integer> age;

  // relationships
  private OptionalProperty<City> city;
  private OptionalProperty<List<Job>> jobs;
}
```

We have our `OptionalPropertyDeserializer` registered to object mapper. It works fine for attributes but we have problem with relationships because our `OptionalProperty` is generic non-collection so it's skipped in `JsonApiEntityModelDeserialize::convertToRepresentationModel` (https://github.com/toedter/spring-hateoas-jsonapi/blob/master/lib/src/main/java/com/toedter/spring/hateoas/jsonapi/JsonApiEntityModelDeserializer.java#L84).

If `OptionalProperty` works for you I can help with implementation to library (also with any other solution).

Thank you!

Adam

**Comment by toedter** [comment]
Thanks for asking, I will think about it.

**Comment by toedter** [comment]
sorry for not reacting in time, I am a little busy right now. I did not forget it and will try to respond before Christmas.

**Comment by sadam21** [comment]
OK, thank you!

**Comment by toedter** [comment]
Hi Adam,

to get the information for the relationships, you can use the @JsonApiRelationships annotation, like

``` Java
@Data
@Entity
@NoArgsConstructor
class Person {
  @Id
  @GeneratedValue
  @JsonIgnore
  private Long id;

  //attributes
  private String name;
  private Integer age;

  // relationships
  @OneToOne
  @JsonApiRelationships("city")
  @JsonIgnore
  private City city;

  @OneToMany
  @JsonApiRelationships("jobs")
  @JsonIgnore
  private List<Job> jobs;

```

Then a person will be serialized to

``` JSON
{
    "data": {
        "type": "persons",
        "attributes": {
            "name": "Kai",
            "age": 56
        },
        "relationships": {
            "city": {
                "data": {
                    "id": "2",
                    "type": "cities"
                }
            },
            "jobs": {
                "data": [
                    {
                        "id": "1",
                        "type": "jobs"
                    }
                ]
            }
        }
    }
}
```

If you want to patch a person, send a PATCH request like

``` JSON
{
    "data": {
        "type": "persons",
        "attributes": {
            "name": "Kay",
            "age": 57
        },
        "relationships": {
            "city": {
                "data": {
                    "id": "4",
                    "type": "cities"
                }
            },
            "jobs": {
                "data": [
                    {
                        "id": "7",
                        "type": "jobs"
                    }
                ]
            }
        }
    }
}
```

If you want to distinguish between a value that should explicitly be set to null and a value that is not set at all in the patch body, one solution could be to use a special marker identifier like  `<<<null>>>` in your patch body. Then your controller could react on set and update the DTO's value to null.

I have created a little demo with your example, you can download it at https://my.hidrive.com/share/ylcmjtbywn
Password is patch-demo

Please re-open if you have further questions or contact me via email kai@toedter.com.
