### ISSUE TITLE
JsonApiData#164 remove id and type field property if entity has a property named "type"

### ISSUE THREAD

**Issue by gaoyang-projects** [toedter/spring-hateoas-jsonapi#53]
use case:
@JsonApiTypeForClass(value = "data")
DataEntity {
  private Long id;
  private String type; // int, long, bool
}

if entity has a property named "type"，JsonApiData remove it from "attributes", output result:
`
{
    "data": {
        "id": "123",
        "type": "data",
        "attributes": {
            // "type":"int" should be here
        }
    }
}
`
JsonApiData#164
`
Map<String, Object> attributeMap = objectMapper.convertValue(content, Map.class);
attributeMap.remove("links");
attributeMap.remove(idField.name);
attributeMap.remove(typeField.name);
`

**Comment by toedter** [comment]
Sorry for not reacting faster, I was on vacation. I'll take a look at it.

**Comment by toedter** [comment]
fixed in the latest snapshot, will be in the next release.
