### ISSUE TITLE
JsonApiModelBuilder is not compatible with ReactiveRepresentationModelAssembler

### ISSUE THREAD

**Issue by jimirocks** [toedter/spring-hateoas-jsonapi#61]
As I commented on #59 (after close), I believe it should be possible to use `JsonApiModelBuilder` while implementing `ReactiveRepresentationModelAssembler` but it's not. See the code, which can't compile on the class declaration:

```java
import com.toedter.spring.hateoas.jsonapi.JsonApiModelBuilder;
import org.springframework.hateoas.CollectionModel;
import org.springframework.hateoas.RepresentationModel;
import org.springframework.hateoas.server.reactive.ReactiveRepresentationModelAssembler;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class JavaAssembler extends ReactiveRepresentationModelAssembler<MyStupidDto, RepresentationModel<?>> {
    @Override
    public Mono<RepresentationModel<?>> toModel(final MyStupidDto entity, final ServerWebExchange exchange) {
        return Mono.just(JsonApiModelBuilder.jsonApiModel().model(entity).build());
    }

    @Override
    public Mono<CollectionModel<RepresentationModel<?>>> toCollectionModel(final Flux<? extends MyStupidDto> entities, final ServerWebExchange exchange) {
        throw new UnsupportedOperationException("not implemented");
    }
}
```

I see two possible solutions:
1. Making `JsonApiModel` public - as suggested in #59 
2. changing the generics of `ReactiveRepresentationModelAssembler` to `<T, D extends RepresentationModel<?>>` from `<T, D extends RepresentationModel<D>>`

**Comment by toedter** [comment]
The code does not compile because `D extends RepresentationModel<D>>` is required in the signature, not `RepresentationModel<?>`. But the only thing a `ReactiveRepresentationModelAssembler` implements, is one line of code in the method `toCollectionModel`. This original method does not make sense  when using `JsonApiModel`s because a `JsonApiModel `can reprersent a collection model itself.

If you want to use an assembler to create representation models, you can easily build your own, like.

``` Java
public class MyAssembler {
    public Mono<RepresentationModel<?>> toModel(final MyStupidDto entity, final ServerWebExchange exchange) {
        return Mono.just(JsonApiModelBuilder.jsonApiModel().model(entity).build());
    }

   Mono<RepresentationModel<?>> toCollectionModel(Flux<? extends MyStupidDto> entities, ServerWebExchange exchange) {
       // use the builder here to create a JsonApiModel based on entities
    }
}
```

So why would you like to re-use  `ReactiveRepresentationModelAssembler` at all?

**Comment by jimirocks** [comment]
> yes, you are right, but the main reason for that is that those assembler interfaces were designed to work mostly with the build-in EntityModel and CollectionModel implementations in mind.

Ahh ha so that was the missing piece of puzzle to understand. Thank you for explanation.

We will go with custom interface....

**Comment by toedter** [comment]
Just fyi, I filed an issue at Spring HATEOAS:
https://github.com/spring-projects/spring-hateoas/issues/1796
