### ISSUE TITLE
JsonApiObject always enables version information

### ISSUE THREAD

**Issue by boe7** [toedter/spring-hateoas-jsonapi#69]
In spring-hateoas-jsonapi:2.0.0, the one-argument constructor for `JsonApiObject(boolean)` disregards the value of the `showVersion` parameter, and always sets the `showVersion` value to true when calling the four-argument constructor.
The effect is that `jsonApiConfiguration.withJsonApiObject(new JsonApiObject(false))` results in the version information being added. As a workaround, `jsonApiConfiguration.withJsonApiObject(null)` can be used to remove the version information, e.g. with the purpose of overriding the configuration for unit testing.

**Comment by toedter** [comment]
thx for reporting this, I'll have a look at it.

**Comment by toedter** [comment]
fix will be in the next release.
