### ISSUE TITLE
Support for JSON:API Data Fetching strategies

### ISSUE THREAD

**Issue by marceloverdijk** [toedter/spring-hateoas-jsonapi#7]
This issue is more of a discussion to see what is possible with this lib and where it is heading to.

The JSON:API spec supports some interesting area's in regards to [Fetching Data](https://jsonapi.org/format/#fetching):

- [Sparse Fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets)
- [Inclusion of Related Resources](https://jsonapi.org/format/#fetching-includes)
- [Sorting](https://jsonapi.org/format/#fetching-sorting)
- [Pagination](https://jsonapi.org/format/#fetching-pagination)
- [Filtering](https://jsonapi.org/format/#fetching-filtering)

These specs really make JSON:API shine as it provides a standardized way to query an api.

It would e.g. be nice to support automatic Sparse Fieldsets and Inclusion of Related Resources based on the HTTP request params.

And for pagination, sorting and filtering maybe an Spring `HandlerMethodArgumentResolver` could be provided to "inject" a paging/sorting/filtering argument in a @RestController method.

Spring Data Commons provides this for standard pageable requests, see [reference docs](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#core.web.basic.paging-and-sorting) and related [apidocs](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/web/package-summary.html).

**Comment by toedter** [comment]
Hi Marcel,

- Automated pagination (meta) is already supported (with` jsonApiModel().pagemeta()`) if the underlying HATEOAS model is a PagedModel, see the findAll method of https://github.com/toedter/spring-hateoas-jsonapi/blob/master/example/src/main/java/com/toedter/spring/hateoas/jsonapi/example/movie/MovieController.java
- Inclusion of related resources is already supporded by the builder, like `jsonApiModel().model(pagedModel).included(director)`
- For sorting and filtering a Spring DATA sorting and paging repository can be used

For sparse fieldsets, I could imagine a utility in the builder that supports that for data, relationships, and included.
This is on the todo list... :)

**Comment by marceloverdijk** [comment]
Hi @toedter,

Yes I understand your points. 
But what I meant is that like Spring Data's [Pageable](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html) (which can be an argument in the controller method), a specific JSON:API argument could be used.
This argument could be used to get all JSON:API spec related parameters like `getPageNumber()` (actually getting `page[number]` param value), `getPageSize()` (getting `page[size]`). But furthermore this argument - or more a wrapper - could also have methods like `isIncluded('movies')`.

Now the controller has arguments like `@RequestParam(value = "page[number]", defaultValue = "0", required = false)` which of course also works, but this is repeated everywhere. As per JSON:API spec the request param names are well defined, so an method argument could be introduced to access all JSON:API related parameters. You see what I mean?

**Comment by toedter** [comment]
Yes, I understand what you mean. Regarding pagination, the JSON:API spec is very flexible:

> Note: JSON:API is agnostic about the pagination strategy used by a server. **Effective pagination strategies include (but are not limited to): page-based, offset-based, and cursor-based**. The page query parameter can be used as a basis for any of these strategies. For example, a page-based strategy might use query parameters such as page[number] and page[size], an offset-based strategy might use page[offset] and page[limit], while a cursor-based strategy might use page[cursor].

So, I am not sure if this flexibility can/should be mapped to a method argument, which implies a statically defined set of predefined attributes.

But for filtering, sorting, and sparse fieldsets this approach could make sense. Let me think about it.

**Comment by marceloverdijk** [comment]
You are right about the pagination (it has been some time I have looked at the specs in detail to be honest. Also the filtering is not set in stone by the spec.

But as you said for sparse fieldsets, includes and sort this could be very covenient.
For pagination I think it's ok to provide a getPageNumber and getPageSize as well as default imo as people are not required to use it.

**Comment by toedter** [comment]
I close this for now and would suggest continuing further discussion either at https://gitter.im/spring-projects/spring-hateoas or at StackOverflow. Sparse fieldsets are still on the todo list.
