### ISSUE TITLE
jsonApiModelBuilder won't add a relationship to modelbuilder

### ISSUE THREAD

**Issue by emoleumassi** [toedter/spring-hateoas-jsonapi#71]
```
final JsonApiModelBuilder jsonApiModel = jsonApiModel()
               .model(modelObject)
               .link(linkTo(methodOn(SomeController.class).findOne(id)).withSelfRel());
      if (condition) {
         List<ModelObject> values =repository(ids)
                                                      .stream()
                                                      .map(ModelObject::new).collect(Collectors.toList());
         jsonApiModel.relationship("key", values);
      }
      EntityModel entityModel = EntityModel.of(jsonApiModel.build());
      return new ResponseEntity<>(entityModel, HttpStatus.OK);
```
i get the object but without the relationship. There are no relationship in responseEntity body but the `values` have some values.

**Comment by emoleumassi** [comment]
i changed the response type to `ResponseEntity<RepresentationModel<?>>` but i have the same issue

**Comment by toedter** [comment]
Could you paste the whole method or provide a link to your code? Then I can take a look.

**Comment by emoleumassi** [comment]
```
@GetMapping("/path/{id}")
   public ResponseEntity<RepresentationModel<?>> findOne(@PathVariable String id,
                                                            @RequestParam(name = "condition", required = false) boolean condition)
   {
      Object object = repository.findById(id);
      if (object== null) {
         throw new ResourceNotFoundException("Could not resolve object for : " + id);
      }

     final JsonApiModelBuilder jsonApiModel = jsonApiModel()
               .model(modelObject)
               .link(linkTo(methodOn(ThisController.class).findOne(id)).withSelfRel());
      if (condition) {
         List<ModelObject> values =repository(ids)
                                                      .stream()
                                                      .map(ModelObject::new).collect(Collectors.toList());
         jsonApiModel.relationship("key", values);
      }
     final RepresentationModel<?> yourModel = jsonApiModel.build();
     return ResponseEntity.ok(yourModel);
```

**Comment by toedter** [comment]
Hm, as long as your `AnotherObject`s have something that could be mapped to a JSON:API resource if (e.g. a field named id), it should work. Could you please paste the Class `AnotherObject`.

**Comment by emoleumassi** [comment]
@Getter
@Setter
@NoArgsConstructor
public class AnotherObject extends RepresentationModel<AnotherObject>
{
   @JsonApiId
   private String id;
   @JsonApiType
   private final String type = "anotherObject";

  // other attributes and constructor

**Comment by toedter** [comment]
You could delete the @JsonApiId annotation here (you only need it for fields that have another name than id).

But if all objects have a valid id set, it should work. Just for testing, try 
``` Java
@JsonApiId
private String id = "1";
```

**Comment by emoleumassi** [comment]
i have it now the responseEntity. Don't ask me how, but it works. 

i use:
```
implementation 'org.springframework.data:spring-data-rest-webmvc:3.7.6'
    implementation 'org.springdoc:springdoc-openapi-hateoas:1.6.14'
    implementation 'org.springdoc:springdoc-openapi-ui:1.6.14'
```

When i use `RepresentationModel<?>` i don't have a wrong representation in swagger. But i use a `EntityModel` i have a correct representation.

**Comment by toedter** [comment]
Yes, this is a drawback when you want to use the Swagger API. I use Spring REST Docs and ePages (https://github.com/ePages-de/restdocs-api-spec) for generating OpenAPI 3 yml files with JSON:API exanmples/schemas.

**Comment by Rezar00** [comment]
Hi @toedter 
I am using spring boot 3.1.1 and also 
`implementation 'org.springdoc:springdoc-openapi-ui:2.0.5'`


I wrapped the request model with EntityModel and consume "application/vnd.api+json" in rest endpoint. 


But on the swagger page, I cannot see the correct representation.
