### ISSUE TITLE
Revert value to null in PATCH

### ISSUE THREAD

**Issue by cgendreau** [toedter/spring-hateoas-jsonapi#77]
We are trying to achieve something very similar to #51 where we need to change back a value to `null` (could be a relationship or an attribute). If we take the Movie example, one could imagine setting the `imdbId` to `ABC ` and then trying to setting it to `null`. So a mechanism would be required to differentiate a value that is set to `null` vs an attribute that was not provided in the PATCH that is `null` due to its initial value.

The `OptionalProperty` suggested in #51 is one way to achieve that. Another way may be to preserve the keys from the Map<String, Object> that is sent to Jackson in `AbstractJsonApiModelDeserializer`. Something like an augmented `EntityModel` could offer a way to check if an attribute/relationship was explicitly provided. Far from perfect, I'm more wondering about potential solution.

Thanks for the library!

**Comment by toedter** [comment]
Thx, since the proposed solution of #51 could be applied, I close this issue. Please re-open when you require changes in the library.
