### ISSUE TITLE
Read JSON:API content type in ResponseEntity

### ISSUE THREAD

**Issue by Rezar00** [toedter/spring-hateoas-jsonapi#80]
Hi, 
I was faced with an issue. Below is my endpoint:

```
    @GetMapping(value = "/{id}", produces = JSON_API_VALUE)
    public ResponseEntity<RepresentationModel<?>> getOrder(@RequestHeader(value = "X-CUSTOMER-ID") Actor actor,
                                                           @PathVariable String id) {

        OrderResponse order = orderService.getOrder(id, actor);
        JsonApiModelBuilder orderJsonApiBuilder = jsonApiModel().model(order);
        if (order.getStatus().equals(OrderStatus.COMPLETED)) {
            List<DocumentServiceResponse> orderedDocuments = this.orderService.getDocumentByOrderId(id);
            orderedDocuments.forEach(document -> document.setLocation(documentServiceEndpoint + "/" + document.getId() + "/body"));
            orderJsonApiBuilder.included(orderedDocuments);
        }

        return ResponseEntity.ok(orderJsonApiBuilder.build());
    }
```

And  Below is my test case:

` var orderStatusResponse = dummyOrderResponseWithStatus(OrderStatus.COMPLETED);
        when(orderService.getOrder(ORDER_ID, ACTOR)).thenReturn(orderStatusResponse);
        when(orderService.getDocumentByOrderId(ORDER_ID)).thenReturn(List.of(dummyDocumentServiceResponse()));
        ResultActions accept = mockMvc.perform(MockMvcRequestBuilders.get("/orders/{id}", ORDER_ID)
                .accept(JSON_API)
                .header(CUSTOMER_ID_HEADER, ACTOR));
        accept
                .andExpect(status().isOk())
                .andExpect(MockMvcResultMatchers.jsonPath("$.id").value(orderStatusResponse.getId()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.included").value(OrderStatus.COMPLETED.toString()));`

I cannot read $.included. It is not present in json path

**Comment by Rezar00** [comment]
@toedter

**Comment by toedter** [comment]
thx for reporting this, I will take a look at it soon.

**Comment by toedter** [comment]
I thing your test case is incorrect, 'included' is never at the same json path level than id, it is always on the level of 'data'. Did you manually check the actual response?

**Comment by Rezar00** [comment]
I tried "$.data" but there is no JSON PATH.
