### ISSUE TITLE
Feature Request: Possibility to answer application/json media type alongside application/vnd.api+json

### ISSUE THREAD

**Issue by msulland** [toedter/spring-hateoas-jsonapi#83]
Hi,

Would it be possible to add a configuration option in JsonApiConfiguration that makes it possible to answer more media types than just application/vnd.api+json? Preferably application/json to make it easier with the frontend.

**Comment by toedter** [comment]
Hm, I think it is better if the services is a s precise as possible describing what it returns. Cold you please elaborate the benefits that it would give the client when more that one media type is returned?
