### ISSUE TITLE
Discussion support?

### ISSUE THREAD

**Issue by timothystone** [toedter/spring-hateoas-jsonapi#86]
I think this project could use GitHub Discussions. I know I would like to initiate some possible PRs but want to speak to existing contributors and leads about ideas and feedback (not just in a PR) as well as initiate discussions on uses of this library.

I have recently followed the [Building REST Services with Spring guide](https://spring.io/guides/tutorial/rest/) and refactored it using this project's documentation to great success. Thank you @toedter (and the contributors) for this work. As an advocate for (and contributor to) the {json:api} project, this is library is in one word: elegant.

<img width="793" alt="image" src="https://github.com/toedter/spring-hateoas-jsonapi/assets/471186/69322508-3a50-46e5-a3c5-c31e8cab225f">

**Comment by toedter** [comment]
Thx for the suggestion. For now I think the issue tracker is good enough for discussions. Maybe I enable it in the future.
