### ISSUE TITLE
Consider to make the media-type configurable

### ISSUE THREAD

**Issue by jimirocks** [toedter/spring-hateoas-jsonapi#9]
Hello, we would love to use this library but for some legal reasons, we would need to configure other media-type (something like `application/vnd.thecompany.api+json`).  Would you consider to add such option to `JsonApiConfiguration`? 

If you agree, I am ready to create pull request.

**Comment by toedter** [comment]
Interesting suggestion, I will think about it when I am back from my vacation, at the end of September.

**Comment by jimirocks** [comment]
@toedter Since I was already trying the way how to achieve that, I created pull request. Just let me know, if you prefer  to design it other way.

**Comment by toedter** [comment]
Thanks for the pull request. Could you please explain what the legal reasons are to prevent you from using the original JSON:API media type? In the meantime, I will take a look at your pull request and check your suggestion with the authors of other media types.

**Comment by jimirocks** [comment]
@toedter Basically the company wants to publish the API with it's own vendor type. Cause of:
1. The several years of API's evolution taught us the using the vendor type is more flexible in case of changing the underlying technology. While the API should remain the same for public the backend could change.
2. Publishing API with some world-wide but specific known media type (like `vnd.api+json`) lead public clients to rely on some behaviour and use some dedicated client libraries, however it can happen the actual implementation follows the spec. different way than the client library expects (ie. CRNK client expects the way CRNK framework implements JSON:API, but our API may behave different while still complying to JSON:API). Using custom vendor media type prevents this kind of misunderstanding - clearly saying this  is something vendor specific (while based on JSON:API).

**Comment by jimirocks** [comment]
@toedter Have you had time yet to consider the reasons and review the code? Should I add/change something?

**Comment by toedter** [comment]
Thanks, I understand the reasons. I have made the class `JsonApiMediaTypeConfiguration` public (it's in the current snapshot). Would it solve your problem if you derive your own MediaTypeConfiguration from it and just override `getMediaTypes()`?

**Comment by jimirocks** [comment]
works for me :+1:  thanks
